# Canonical English UI resources and fallback values.
# Keep keys stable; format placeholders are populated by Controller.ps1.
@{
    'MainWindow.Title' = 'My Little Supervision'
    'Status.Unknown' = 'Unknown'
    'Status.Running' = 'Running'
    'Status.Online' = 'Online'
    'Status.Degraded' = 'Degraded'
    'Status.Offline' = 'Offline'
    'Status.Error' = 'Error'
    'Status.Disabled' = 'Disabled'
    'Menu.File' = 'File'
    'Menu.View' = 'View'
    'Menu.Tools' = 'Tools'
    'Menu.Help' = 'Help'
    'Action.Open' = 'Open configuration…'
    'Action.Export' = 'Export CSV…'
    'Action.Exit' = 'Exit'
    'Action.Pause' = 'Pause automatic checks'
    'Action.Refresh' = 'Refresh'
    'Action.Reload' = 'Reload configuration'
    'Action.Logs' = 'Open log folder'
    'Action.About' = 'About'
    'Action.Folder' = 'Open configuration folder'
    'Label.Groups' = 'Groups'
    'Label.Search' = 'Search:'
    'Label.Group' = 'Group:'
    'Label.ErrorsOnly' = 'Only incidents'
    'Label.All' = 'All'
    'Column.Name' = 'Resource'
    'Column.Type' = 'Type'
    'Column.Target' = 'Host / URL'
    'Column.Ping' = 'Ping'
    'Column.Service' = 'TCP'
    'Column.Http' = 'HTTP'
    'Column.Checked' = 'Last check'
    'Column.Status' = 'Status'
    'Column.Duration' = 'Duration (ms)'
    'Column.Message' = 'Message'
    'Tab.Details' = 'Details'
    'Tab.History' = 'History'
    'Tab.Log' = 'Journal'
    'Label.Select' = 'Select a resource to view its details.'
    'Label.Summary' = '{0} resources | {1} online | {2} slow | {3} incidents'
    'Label.Running' = 'Checks in progress…'
    'Label.Paused' = 'Automatic checks paused'
    'Label.Ready' = 'Next check: {0}'
    'Label.Details' = 'Target: {0}
Type: {1}
Last check: {2}
Duration: {3} ms
Status: {4}
Message: {5}
Session success rate: {6}

{7}'
    'Label.PingNote' = 'An ICMP failure does not prove that the host or its services are down.'
    'Label.HistoryNote' = 'History is kept in memory for the last 200 results per check.'
    'Error.Configuration' = 'Cannot load configuration. The current configuration is retained. Check the file schema and values.'
    'Error.Action' = 'The action failed. Check the file location and your access permissions.'
    'Error.Logging' = 'Log file unavailable'
    'About.Text' = 'My Little Supervision
Ping, HTTP and TCP monitoring.
Windows PowerShell 5.1 / WPF.
Configuration is stored in external PSD1 files.'
    'Message.Disabled' = 'Check disabled'
    'Message.Unknown' = 'Not checked yet'
    'Message.HttpStatus' = 'HTTP status: {0}'
    'Message.PingReply' = 'ICMP reply: {0}'
    'Message.TcpConnected' = 'TCP connection established'
    'Message.Timeout' = 'Check timed out'
    'Message.DnsFailure' = 'DNS resolution failed'
    'Message.NetworkFailure' = 'Network check failed ({0})'
    'Message.WorkerFailure' = 'The check worker failed'
    'Dialog.Configuration' = 'PowerShell configuration (*.psd1)|*.psd1'
    'Dialog.Csv' = 'CSV files (*.csv)|*.csv'
    'Web.Started' = 'My Little Supervision is running at {0} — press Ctrl+C to stop.'
    'Web.BrowserUnavailable' = 'Open the printed address in your browser.'
    'Web.Configuration' = 'Configuration'
    'Web.ConfigurationPath' = 'Absolute PSD1 file path:'
    'Web.LogPath' = 'Log folder: {0}'
    'Web.Actions' = 'Actions'
    'Web.Filters' = 'Filters'
    'Web.ConfigurationPending' = 'Waiting for active checks before loading configuration…'
    'Web.Disconnected' = 'Connection to the local monitor was lost. Retrying…'
}
