@{
    'MainWindow.Title' = 'My Little Supervision'
    'Status.Unknown' = 'Inconnu'
    'Status.Running' = 'En cours'
    'Status.Online' = 'Disponible'
    'Status.Degraded' = 'Partiellement disponible'
    'Status.Offline' = 'Indisponible'
    'Status.Error' = 'Erreur'
    'Status.Disabled' = 'Inactif'
    'Menu.File' = 'Fichier'
    'Menu.View' = 'Affichage'
    'Menu.Tools' = 'Outils'
    'Menu.Help' = 'Aide'
    'Action.Open' = 'Ouvrir une configuration…'
    'Action.Export' = 'Exporter en CSV…'
    'Action.Exit' = 'Quitter'
    'Action.Pause' = 'Suspendre les contrôles automatiques'
    'Action.Refresh' = 'Rafraîchir'
    'Action.Reload' = 'Recharger la configuration'
    'Action.Logs' = 'Ouvrir le dossier des journaux'
    'Action.About' = 'À propos'
    'Action.Folder' = 'Ouvrir le dossier de configuration'
    'Label.Groups' = 'Groupes'
    'Label.Search' = 'Rechercher :'
    'Label.Group' = 'Groupe :'
    'Label.ErrorsOnly' = 'Seulement les incidents'
    'Label.All' = 'Tous'
    'Column.Name' = 'Ressource'
    'Column.Type' = 'Type'
    'Column.Target' = 'Hôte / URL'
    'Column.Ping' = 'Ping'
    'Column.Service' = 'TCP'
    'Column.Http' = 'HTTP'
    'Column.Checked' = 'Vérification'
    'Column.Status' = 'État'
    'Column.Duration' = 'Durée (ms)'
    'Column.Message' = 'Message'
    'Tab.Details' = 'Détails'
    'Tab.History' = 'Historique'
    'Tab.Log' = 'Journal'
    'Label.Select' = 'Sélectionnez une ressource pour afficher ses détails.'
    'Label.Summary' = '{0} ressources | {1} disponibles | {2} lentes | {3} incidents'
    'Label.Running' = 'Contrôles en cours…'
    'Label.Paused' = 'Contrôles automatiques suspendus'
    'Label.Ready' = 'Prochain contrôle : {0}'
    'Label.Details' = 'Cible : {0}
Type : {1}
Vérification : {2}
Durée : {3} ms
État : {4}
Message : {5}
Réussite de la session : {6}

{7}'
    'Label.PingNote' = 'Un échec ICMP ne prouve pas que la machine ou ses services sont indisponibles.'
    'Label.HistoryNote' = 'L''historique conserve en mémoire les 200 derniers résultats par contrôle.'
    'Error.Configuration' = 'Impossible de charger la configuration. La configuration actuelle est conservée. Vérifiez le schéma et les valeurs du fichier.'
    'Error.Action' = 'L''action a échoué. Vérifiez le chemin et vos droits d''accès.'
    'Error.Logging' = 'Fichier journal inaccessible'
    'About.Text' = 'My Little Supervision
Supervision Ping, HTTP et TCP.
Windows PowerShell 5.1 / WPF.
Configuration dans des fichiers PSD1 externes.'
    'Message.Disabled' = 'Contrôle désactivé'
    'Message.Unknown' = 'Pas encore vérifié'
    'Message.HttpStatus' = 'Statut HTTP : {0}'
    'Message.PingReply' = 'Réponse ICMP : {0}'
    'Message.TcpConnected' = 'Connexion TCP établie'
    'Message.Timeout' = 'Délai de contrôle dépassé'
    'Message.DnsFailure' = 'Échec de résolution DNS'
    'Message.NetworkFailure' = 'Échec du contrôle réseau ({0})'
    'Message.WorkerFailure' = 'Échec du processus de contrôle'
    'Dialog.Configuration' = 'Configuration PowerShell (*.psd1)|*.psd1'
    'Dialog.Csv' = 'Fichiers CSV (*.csv)|*.csv'
}
